name: Generate Snake

on:
  # Run automatically every 6 hours
  schedule:
    - cron: "0 */6 * * *"
  
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Blissmal
          outputs: dist/github-snake.svg
      
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
